# Generated by Django 5.0.1 on 2024-01-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawPatrol', '0003_heroe_personalizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='heroe_personalizado',
        ),
    ]
