# Generated by Django 5.0.1 on 2024-01-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawPatrol', '0008_favorito_delete_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='foto',
        ),
    ]
