# Generated by Django 5.0.1 on 2024-01-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawPatrol', '0009_remove_favorito_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorito',
        ),
    ]
