# Generated by Django 5.0.1 on 2024-01-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawPatrol', '0012_alter_favorito_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorito',
        ),
    ]
