# Generated by Django 5.0.1 on 2024-01-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawPatrol', '0016_remove_favorito_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Heroes'),
        ),
    ]
